name: Benchmark
on: [push]

jobs:
  convert-push-images:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: imjasonh/setup-crane@v0.1
      - name: Install tools
        run: sudo bash tools/install-nerdctl.sh
      - name: Convert and push images
        run: |
          sudo -s
          bash tools/start-containerd.sh
          echo "${{ secrets.GITHUB_TOKEN }}" | nerdctl login ghcr.io -u $ --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | crane auth login -u $ --password-stdin ghcr.io
          crane manifest ghcr.io/gabrieldemarmiesse/estargz-images/alpine:3.15.3-org
          python -u ./convert_and_push_images.py
