name: Benchmark
on: [push]

jobs:
  convert-push-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: imjasonh/setup-crane@v0.1
      - name: Install tools
        run: sudo bash tools/install-nerdctl.sh
      - name: Login to registry with nerdctl
        run: echo ${{ secrets.REPOSITORY_PASSWORD }} | sudo nerdctl login -u  ${{ secrets.REPOSITORY_USERNAME }} --password-stdin
      - name: Login to registry with crane
        run: echo ${{ secrets.REPOSITORY_PASSWORD }} | sudo crane auth login -u  ${{ secrets.REPOSITORY_USERNAME }} --password-stdin docker.io
      - name: Convert and push images
        run: |
          sudo bash tools/start-containerd.sh
          sudo python -u ./convert_and_push_images.py
